config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :vendors do
      collection do
        post :update_positions
      end
    end
    get 'vendor_settings' => 'vendor_settings#edit'
    patch 'vendor_settings' => 'vendor_settings#update'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      namespace :storefront do
        resources :vendors, only: [:show]
      end
    end
    namespace :v1 do
      resources :vendors
    end
  end
end

app/models/spree/vendor.rb
module Spree
  class Vendor < Spree::Base
    extend FriendlyId

    acts_as_paranoid
    acts_as_list column: :priority
    friendly_id :name, use: %i[slugged history]

    validates :name,
              presence: true,
              uniqueness: { case_sensitive: false }

    validates :slug, uniqueness: true
    validates_associated :image if Spree.version.to_f >= 3.6

    validates :notification_email, email: true, allow_blank: true

    with_options dependent: :destroy do
      has_one :image, as: :viewable, dependent: :destroy, class_name: 'Spree::VendorImage'
      has_many :commissions, class_name: 'Spree::OrderCommission'
      has_many :vendor_users

      SpreeMultiVendor::Config[:vendorized_models].uniq.compact.each do |model|
        has_many model.pluralize.to_sym
      end
    end

    #belongs_to :state, class_name: 'Spree::State', optional: true
    #belongs_to :country, class_name: 'Spree::Country'
      belongs_to :address, class_name: 'Spree::Address'
      accepts_nested_attributes_for :address
    
    
    
    
    has_many :users, through: :vendor_users, class_name: Spree.user_class.to_s

    after_create :create_stock_location
    after_update :update_stock_location_names

    state_machine :state, initial: :pending do
      event :activate do
        transition to: :active
      end

      event :block do
        transition to: :blocked
      end
    end

    scope :active, -> { where(state: 'active') }

    self.whitelisted_ransackable_attributes = %w[name state]

    def update_notification_email(email)
      update(notification_email: email)
    end

    # Spree Globalize support
    # https://github.com/spree-contrib/spree_multi_vendor/issues/104
    if defined?(SpreeGlobalize)
      attr_accessor :translations_attributes
      translates :name,
                 :about_us,
                 :contact_us,
                 :slug, fallbacks_for_empty_translations: true
    end

    private

    def create_stock_location
      stock_locations.where(name: name, country: Spree::Country.default).first_or_create!
    end

    def should_generate_new_friendly_id?
      slug.blank? || name_changed?
    end

    def update_stock_location_names
      if (Spree.version.to_f < 3.5 && self.name_changed?) || (Spree.version.to_f >= 3.5 && saved_changes&.include?(:name))
        stock_locations.update_all({ name: name })
      end
    end
  end
end

app/controllers/spree/admin/vendors_controller.rb
module Spree
  module Admin
    class VendorsController < ResourceController
       #before_action :set_country, only: :new

      def create
        if permitted_resource_params[:image]
          @vendor.build_image(attachment: permitted_resource_params.delete(:image))
        end
        super
      end

      def update
        @vendor.address = Spree::Address.immutable_merge(@vendor.address, permitted_resource_params[:address_attributes])
        if permitted_resource_params[:image]
          @vendor.create_image(attachment: permitted_resource_params.delete(:image))
        end
        format_translations if defined? SpreeGlobalize
        super
      end

      def update_positions
        params[:positions].each do |id, position|
          vendor = Spree::Vendor.find(id)
          vendor.set_list_position(position)
        end

        respond_to do |format|
          format.js { render plain: 'Ok' }
        end
      end

 def edit
    @vendor.address = Spree::Address.build_default unless @vendor.address.present?
    respond_with(@vendor) do |format|
      format.html { render :layout => !request.xhr? }
      format.js   { render :layout => false }
    end
  end

  def new
    @vendor.address = Spree::Address.build_default
  end

      private

      def find_resource
        Vendor.with_deleted.friendly.find(params[:id])
      end

      def collection
        params[:q] = {} if params[:q].blank?
        vendors = super.order(priority: :asc)
        @search = vendors.ransack(params[:q])

        @collection = @search.result.
            page(params[:page]).
            per(params[:per_page])
      end
      
      
      def set_country
        vendor.country = current_store.default_country
        unless vendor.country
          flash[:error] = Spree.t(:stock_locations_need_a_default_country)
          #redirect_to spree.admin_stock_locations_path
        end
      end

      def format_translations
        return if params[:vendor][:translations_attributes].blank?
        params[:vendor][:translations_attributes].each do |_, data|
          translation = @vendor.translations.find_or_create_by(locale: data[:locale])
          translation.name = data[:name]
          translation.about_us = data[:about_us]
          translation.contact_us = data[:contact_us]
          translation.slug = data[:slug]
          translation.save!
        end
      end
    end
  end
end

app/controllers/spree/api/v1/vendors_controller.rb
module Spree
  module Api
    module V1
      class VendorsController < Spree::Api::BaseController
        def index
          @vendors = if params[:ids].present?
                       scope.where(id: params[:ids].split(','))
                     else
                       scope.load.ransack(
                         params[:q]
                       ).result
                     end
          respond_with(@vendors)
        end

        def show
          @vendor = scope.find(params[:id])
          authorize! :show, @vendor
          respond_with(@vendor)
        end

        def create
          authorize! :create, Spree::Vendor
          @vendor = Spree::Vendor.new(vendor_params)
          if @vendor.save
            render :show, status: 201
          else
            invalid_resource!(@vendor)
          end
        end

        def update
          @vendor = scope.find(params[:id])
          authorize! :update, @vendor
          if @vendor.update(vendor_params)
            render :show
          else
            invalid_resource!(@vendor)
          end
        end

        def destroy
          @vendor = scope.find(params[:id])
          authorize! :destroy, @vendor
          @vendor.destroy
          render plain: nil, status: 204
        end

        private

        def scope
          Spree::Vendor.accessible_by(current_ability)
        end

        def vendor_params
          params.require(:vendor).permit(Spree::PermittedAttributes.vendor_attributes)
        end
      end
    end
  end
end

app/controllers/spree/api/v2/storefront/vendors_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        class VendorsController < ::Spree::Api::V2::ResourceController

          private

          def model_class
            ::Spree::Vendor
          end

          def scope
            ::Spree::Vendor.active
          end

          def resource
            scope.find_by(slug: params[:id]) || scope.find(params[:id])
          end

          def resource_serializer
            Spree::V2::Storefront::VendorSerializer
          end
        end
      end
    end
  end
end

app/helpers/spree/admin/vendor_helper.rb
module Spree
  module Admin
    module VendorHelper
      def current_spree_vendor
        if current_spree_user.vendors.any? && (!current_spree_user.respond_to?(:has_spree_role?) || !current_spree_user.has_spree_role?(:admin))
          current_spree_user.vendors.first
        end
      end

      def vendor_state_options
        @vendor_state_options ||= Spree::Vendor.state_machines[:state].states.collect { |s| [Spree.t("vendor_states.#{s.name}"), s.value] }
      end
    end
  end
end

app/helpers/spree/api/vendor_helper.rb
module Spree
  module Api
    module VendorHelper
      def current_spree_vendor
        if current_api_user.vendors.any? && (!current_api_user.respond_to?(:has_spree_role?) || !current_api_user.has_spree_role?(:admin))
          current_api_user.vendors.first
        end
      end
    end
  end
end

app/views/spree/admin/vendors/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @vendor } %>

<div data-hook="vendor_address_wrapper" class="col-md-6">
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t('contact_address') %></legend>
    <%= f.fields_for :address do |contact_form| %>
      <%= render :partial => 'spree/admin/shared/address_form', :locals => { :f => contact_form, :name => Spree.t(:contact_address), :type => "shipping" } %>
    <% end %>
  </fieldset>
</div>

<div class="form-group">
  <%= f.field_container :name do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  <% end %>
  <%= f.field_container :about_us do %>
    <%= f.label :about_us %>
    <%= f.text_area :about_us, class: 'form-control' %>
  <% end %>
  <%= f.field_container :contact_us do %>
    <%= f.label :contact_us %>
    <%= f.text_area :contact_us, class: 'form-control' %>
  <% end %>
  <%= f.field_container :state do %>
    <%= f.label :state %>
    <%= f.select :state,
      options_for_select(vendor_state_options, selected: @vendor.state),
      {}, class: 'select2', required: :required %>
  <% end %>
  <% if Spree.version.to_f >= 3.6 %>
    <%= f.field_container :image do %>
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= image_tag main_app.url_for(@vendor.image.url(:small)) if @vendor.image %>
    <% end %>
  <% end %>
  <%= f.field_container :commission_rate do %>
    <%= f.label :commission_rate %>
    <%= f.number_field :commission_rate, step: '0.01', class: 'form-control' %>
  <% end %>
  <%= f.field_container :notification_email do%>
    <%= f.label :notification_email %>
    <%= f.email_field :notification_email, class: 'form-control' %>
  <% end %>
  
  
<%= f.field_container :address1 do %>
    <%= f.label :address1, Spree.t(:street_address) %>
    <%= f.text_field :address1, class: 'form-control' %>
<% end %>
  
  <%= f.field_container :address2 do %>
    <%= f.label :address2, Spree.t(:street_address_2) %>
    <%= f.text_field :address2, class: 'form-control' %>
  <% end %>

<%= f.field_container :city do %>
    <%= f.label :city, Spree.t(:city) %>
    <%= f.text_field :city, class: 'form-control' %>
   <% end %>

<%= f.field_container :zipcode do %>
    <%= f.label :zipcode, Spree.t(:zip) %>
    <%= f.text_field :zipcode, class: 'form-control' %>
   <% end %>

<%= f.field_container :phone do %>
    <%= f.label :phone, Spree.t(:phone) %>
    <%= f.phone_field :phone, class: 'form-control' %>
   <% end %>


  

</div>

app/views/spree/admin/vendors/edit.html.erb
<% content_for :page_title do %>
  <%= link_to plural_resource_name(Spree::Vendor), spree.admin_vendors_url %> /
  <%= @vendor.name %>
<% end %>

<%= form_for [:admin, @vendor] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/vendors/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(plural_resource_name(Spree::Vendor)) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_vendor), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_vendor' } %>
<% end if can?(:create, Spree::Vendor) %>

<% content_for :table_filter do %>
  <div data-hook="admin_vendors_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, tabindex: 1, class: "form-control js-quick-search-target" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_state_in, Spree.t(:state) %>
            <%= f.select :state_in, options_for_select(vendor_state_options), { multiple: 'please select' }, class: 'select2', multiple: true %>
          </div>
        </div>
      </div>
      <div data-hook="admin_vendors_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @vendors.any? %>
  <table class="table sortable" data-hook="vendors_table" data-sortable-link="<%= update_positions_admin_vendors_url %>">
    <thead>
      <tr data-hook="vendors_header">
        <th>
          <%= Spree.t(:user) %>
        </th>
        <th>
          <%= sort_link @search, :name, I18n.t(:name, scope: 'activerecord.attributes.spree/vendor') %>
        </th>
        <th>
          <%= sort_link @search, :state, I18n.t(:state, scope: 'activerecord.attributes.spree/vendor') %>
        </th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @vendors.each do |vendor| %>
        <tr id="<%= spree_dom_id vendor %>" data-hook="vendors_row">
          <td>
            <%= vendor.users.first.email rescue nil %>
          </td>
          <td>
            <%= vendor.name %>
          </td>
          <td>
            <span class="label label-<%= vendor.state.downcase %>"><%= vendor.state.humanize.downcase %></span>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= vendor.state %>"></span>
          </td>
          <td class="actions actions-2 text-right">
            <%= link_to_edit vendor, no_text: true, class: 'edit' if can?(:edit, vendor) %>
            <!-- Add translation icon support -->
            <%= link_to_with_icon 'translate',
                                  nil,
                                  spree.admin_translations_path('vendor', vendor.id),
                                  title: Spree.t(:'i18n.translations'),
                                  class: 'btn btn-sm btn-primary' if defined? (SpreeGlobalize)%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Vendor)) %>
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/admin/vendors/new.html.erb
<% content_for :page_title do %>
  <%= link_to plural_resource_name(Spree::Vendor), spree.admin_vendors_url %> /
  <%= Spree.t(:new_vendor) %>
<% end %>

<%= form_for [:admin, @vendor] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>