config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :vendors do
      collection do
        post :update_positions
      end
    end
    get 'vendor_settings' => 'vendor_settings#edit'
    patch 'vendor_settings' => 'vendor_settings#update'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
      namespace :storefront do
        resources :vendors, only: [:show]
      end
    end
    namespace :v1 do
      resources :vendors
    end
  end
end

app/controllers/spree/admin/vendor_settings_controller.rb
module Spree
  module Admin
    class VendorSettingsController < Spree::Admin::BaseController
      before_action :authorize
      #before_action :set_country, only: :new
      before_action :load_vendor
      

      def update
        if vendor_params[:image]
          @vendor.create_image(attachment: vendor_params[:image])
        end
        if @vendor.update(vendor_params.except(:image))
          redirect_to admin_vendor_settings_path
        else
          render :edit
        end
      end

      private

      def authorize
        authorize! :manage, :vendor_settings
      end

      def load_vendor
        @vendor = current_spree_vendor
        raise ActiveRecord::RecordNotFound unless @vendor
      end
      

      def vendor_params
        params.require(:vendor).permit(Spree::PermittedAttributes.vendor_attributes)
      end
    end
  end
end

app/views/spree/admin/vendor_settings/edit.html.erb
<% content_for :page_title do %>
  <%= @vendor.name %>
<% end %>

<%= form_for [:admin, @vendor], url: admin_vendor_settings_url do |f| %>
  <fieldset>
    <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @vendor } %>
    <div class="form-group">
      <%= f.field_container :name do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      <% end %>
    </div>
    <% if Spree.version.to_f >= 3.6 %>
      <div class="form-group">
        <%= f.field_container :image do %>
          <%= f.label :image %>
          <%= f.file_field :image %>
          <%= image_tag main_app.url_for(@vendor.image.url(:small)) if @vendor.image %>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.field_container :about_us do %>
        <%= f.label :about_us %>
        <%= f.text_area :about_us, class: 'form-control' %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.field_container :contact_us do %>
        <%= f.label :contact_us %>
        <%= f.text_area :contact_us, class: 'form-control' %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.field_container :notification_email do %>
        <%= f.label :notification_email %>
        <%= f.email_field :notification_email, class: 'form-control' %>
      <% end %>
    </div>
    
    
  <div class="form-group">
    <%= f.field_container :address1 do %>
    <%= f.label :address1, Spree.t(:street_address) %>
    <%= f.text_field :address1, class: 'form-control' %>
    <% end %>
  </div>
    
  <div class="form-group">
    <%= f.field_container :address2 do %>
    <%= f.label :address2, Spree.t(:street_address_2) %>
    <%= f.text_field :address2, class: 'form-control' %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.field_container :city do %>
    <%= f.label :city, Spree.t(:city) %>
    <%= f.text_field :city, class: 'form-control' %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.field_container :zipcode do %>
    <%= f.label :zipcode, Spree.t(:zip) %>
    <%= f.text_field :zipcode, class: 'form-control' %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.field_container :phone do %>
    <%= f.label :phone, Spree.t(:phone) %>
    <%= f.phone_field :phone, class: 'form-control' %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.field_container :country_id do %>
    <%= f.label :country_id, Spree.t(:country) %>
    <span id="country"><%= f.collection_select :country_id, available_countries, :id, :name, {}, { class: 'select2' } %></span>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.field_container :state_id do %>
    <% if f.object.country %>
      <%= f.label :state_id, Spree.t(:state) %>
      <span id="state" class="region">
        <%= f.text_field :state_name, style: "#{f.object.country.states.empty? ? '' : 'display: none;'}", disabled: !f.object.country.states.empty?, class: 'state_name form-control' %>
        <%= f.collection_select :state_id, f.object.country.states.sort, :id, :name, { include_blank: true }, {class: 'select2-clear', style: "#{f.object.country.states.empty? ? 'display: none;' : '' };", disabled: f.object.country.states.empty?} %>
      </span>
    <% end %>
    <% end %>
  </div>
    
    
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_vendor_settings_url, icon: 'delete' %>
    </div>
  </fieldset>
<% end %>